version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - rabbitmq
      - ollama

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./Modelfile:/Modelfile
   

  worker:
    build: .
    command: python worker.py
    depends_on:
      - rabbitmq
      - ollama

volumes:
  ollama_data:
